# Generated by Django 3.2.15 on 2022-08-23 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_alter_profile_profileimg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
